export const dummyWordsData = [
  {
    wordCatEn: "forests",
    wordEn: "earth",
    wordProtoAn: "*taneq",
  },
  {
    wordCatEn: "forests",
    wordEn: "plant",
    wordProtoAn: "*agdaw",
  },
  {
    wordCatEn: "forests",
    wordEn: "flower",
    wordProtoAn: "*tsdadf",
  },
  {
    wordCatEn: "seas",
    wordEn: "beach",
    wordProtoAn: "*asdsda",
  },
  {
    wordCatEn: "seas",
    wordEn: "sand",
    wordProtoAn: "*sadwad",
  },
  {
    wordCatEn: "skies",
    wordEn: "birds",
    wordProtoAn: "*sadsnflej",
  },
  {
    wordCatEn: "skies",
    wordEn: "clouds",
    wordProtoAn: "*xasxas",
  },
];

export const dummyLangData = [
  {
    wordEn: "earth",
    wordAn: "qaBan",
    langAn: "Atayal",
    langAnCode: "ata",
    langGroup: "Formosan",
    langRegion: "Formosan",
    lat: 20.3,
    long: 113.45,
  },
  {
    wordEn: "earth",
    wordAn: "ssaaff",
    langAn: "Bunun",
    langAnCode: "bun",
    langGroup: "Formosan",
    langRegion: "Formosan",
    lat: 22.3,
    long: 113.45,
  },
  {
    wordEn: "plant",
    wordAn: "sxsxaf",
    langAn: "Hiligaynon",
    langAnCode: "hil",
    langGroup: "Philippines",
    langRegion: "Malayo-Polynesian",
    lat: 23.3,
    long: 134.45,
  },
  {
    wordEn: "plant",
    wordAn: "qaBan",
    langAn: "Haaggga",
    langAnCode: "bun",
    langGroup: "Solomonic",
    langRegion: "Melanesian",
    lat: 21.3,
    long: 135.45,
  },
  {
    wordEn: "flower",
    wordAn: "asdafas",
    langAn: "Hawaiian",
    langAnCode: "haw",
    langGroup: "Oceanic",
    langRegion: "Polynesian",
    lat: 21.3,
    long: 135.45,
  },
  {
    wordEn: "flower",
    wordAn: "asdafas",
    langAn: "Hawaiian",
    langAnCode: "haw",
    langGroup: "Oceanic",
    langRegion: "Polynesian",
    lat: 21.3,
    long: 130.45,
  },
  {
    wordEn: "beach",
    wordAn: "oshdcs",
    langAn: "Hawaiian",
    langAnCode: "haw",
    langGroup: "Oceanic",
    langRegion: "Polynesian",
    lat: 21.3,
    long: 125.45,
  },
  {
    wordEn: "beach",
    wordAn: "dsiuvhdi",
    langAn: "Hawaiian",
    langAnCode: "haw",
    langGroup: "Oceanic",
    langRegion: "Polynesian",
    lat: 21.3,
    long: 125.45,
  },
  {
    wordEn: "sand",
    wordAn: "vvdfvsdvse",
    langAn: "Hawaiian",
    langAnCode: "haw",
    langGroup: "Oceanic",
    langRegion: "Polynesian",
    lat: 21.3,
    long: 125.45,
  },
  {
    wordEn: "birds",
    wordAn: "dcdcdcs",
    langAn: "Hawaiian",
    langAnCode: "haw",
    langGroup: "Oceanic",
    langRegion: "Polynesian",
    lat: 21.3,
    long: 125.42,
  },
  {
    wordEn: "birds",
    wordAn: "dfgdlkmrd",
    langAn: "Hawaiian",
    langAnCode: "haw",
    langGroup: "Oceanic",
    langRegion: "Polynesian",
    lat: 21.3,
    long: 125.45,
  },
  {
    wordEn: "clouds",
    wordAn: "sdcsdcse",
    langAn: "Hawaiian",
    langAnCode: "haw",
    langGroup: "Oceanic",
    langRegion: "Polynesian",
    lat: 23.3,
    long: 123.45,
  },
];

export const dummyRegionData = [
  {
    langRegion: "Formosan",
    distFromHomeland: 0,
  },
  {
    langRegion: "Maritime SEA",
    distFromHomeland: 2850,
  },
  {
    langRegion: "Micronesia",
    distFromHomeland: 4500,
  },
  {
    langRegion: "Melanesia",
    distFromHomeland: 6000,
  },
  {
    langRegion: "Polynesia",
    distFromHomeland: 9400,
  },
];
