export const dummyWordsData = [
  {
    wordCatEn: "forests",
    wordEn: "earth",
    wordProtoAn: "*taneq",
    wordAn: "qaBan",
  },
  {
    wordCatEn: "forests",
    wordEn: "plant",
    wordProtoAn: "*agdaw",
    wordAn: "hagsa",
  },
  {
    wordCatEn: "forests",
    wordEn: "flower",
    wordProtoAn: "*tsdadf",
    wordAn: "sadsjjs",
  },
  {
    wordCatEn: "seas",
    wordEn: "beach",
    wordProtoAn: "*asdsda",
    wordAn: "vgdscd",
  },
  {
    wordCatEn: "seas",
    wordEn: "sand",
    wordProtoAn: "*sadwad",
    wordAn: "czcdzd",
  },
  {
    wordCatEn: "skies",
    wordEn: "birds",
    wordProtoAn: "*sadsnflej",
    wordAn: "csdsdcs",
  },
  {
    wordCatEn: "skies",
    wordEn: "clouds",
    wordProtoAn: "*xasxas",
    wordAn: "kuikuk",
  },
];

export const dummyLangData = [
  {
    wordEn: "earth",
    wordAn: "qaBan",
    langAn: "Atayal",
    langAnCode: "ata",
    langGroup: "Formosan",
    langRegion: "Formosan",
    lat: 20.3,
    long: 113.45,
  },
  {
    wordEn: "earth",
    wordAn: "ssaaff",
    langAn: "Bunun",
    langAnCode: "bun",
    langGroup: "Formosan",
    langRegion: "Formosan",
    lat: 22.3,
    long: 113.45,
  },
  {
    wordEn: "earth",
    wordAn: "sxsxaf",
    langAn: "Hiligaynon",
    langAnCode: "hil",
    langGroup: "Philippines",
    langRegion: "Malayo-Polynesian",
    lat: 20.3,
    long: 121.45,
  },
  {
    wordEn: "earth",
    wordAn: "qaBan",
    langAn: "Haaggga",
    langAnCode: "bun",
    langGroup: "Solomonic",
    langRegion: "Melanesian",
    lat: 21.3,
    long: 135.45,
  },
  {
    wordEn: "earth",
    wordAn: "asdafas",
    langAn: "Hawaiian",
    langAnCode: "haw",
    langGroup: "Oceanic",
    langRegion: "Polynesian",
    lat: 21.3,
    long: 145.45,
  },
];
